exports.commons = {
    identifier: {
        name: {
            en: "Identifier (IPEI)",
            de: "Kennung (IPEI)",
            ru: "Идентификатор (IPEI)",
            pt: "Identificação (IPEI)",
            nl: "Identif (IPEI)",
            fr: "Identifiant (IPEI)",
            it: "Identificazione (IPEI)",
            es: "Identifier (IPEI)",
            pl: "Identyfikator (IPEI)",
            uk: "Виявлення (IPEI)",
            "zh-cn": "Identifier (IPEI)",
        },
        type: "string",
        role: "info",
        write: false,
        read: true,
        def: "",
    },
    id: {
        name: {
            en: "ID",
            de: "ID",
            ru: "КОД",
            pt: "ID",
            nl: "ID",
            fr: "ID",
            it: "ID",
            es: "ID",
            pl: "ID",
            uk: "ІМ'Я",
            "zh-cn": "ID ",
        },
        type: "number",
        role: "info",
        write: false,
        read: true,
        def: 0,
    },
    functionbitmask: {
        name: {
            en: "Bit mask",
            de: "Bitmaske",
            ru: "Bit маска",
            pt: "Máscara de bocado",
            nl: "Bit masker",
            fr: "Masque Bit",
            it: "Maschera bit",
            es: "Máscara de bits",
            pl: "Maska",
            uk: "Бітна маска",
            "zh-cn": "Bit mask",
        },
        type: "string",
        role: "info",
        write: false,
        read: true,
        def: "",
    },
    fwversion: {
        name: {
            en: "Version",
            de: "Version",
            ru: "Версия",
            pt: "Versão",
            nl: "Vers",
            fr: "Version",
            it: "Versione",
            es: "Versión",
            pl: "Wersja",
            uk: "Редагування",
            "zh-cn": "目 录",
        },
        type: "string",
        role: "info.firmware",
        write: false,
        read: true,
        def: "",
    },
    manufacturer: {
        name: {
            en: "Manufacturer",
            de: "Hersteller",
            ru: "Производитель",
            pt: "Fabricante",
            nl: "Manufactur",
            fr: "Fabricant",
            it: "Produttore",
            es: "Fabricantes",
            pl: "Manufacturer",
            uk: "Продукція",
            "zh-cn": "制造商",
        },
        type: "string",
        role: "info",
        write: false,
        read: true,
        def: "",
    },
    productname: {
        name: {
            en: "Productname",
            de: "Erzeugnisname",
            ru: "Имя продукта",
            pt: "Nome do produto",
            nl: "Product naam",
            fr: "Nom du produit",
            it: "Nome del prodotto",
            es: "Nombre del producto",
            pl: "Nazwa",
            uk: "Назва продукту",
            "zh-cn": "产品名称",
        },
        type: "string",
        role: "info",
        write: false,
        read: true,
        def: "",
    },
    present: {
        name: {
            en: "Device online",
            de: "Gerät online",
            ru: "Устройство онлайн",
            pt: "Dispositivo online",
            nl: "Device online",
            fr: "Appareil en ligne",
            it: "Dispositivo online",
            es: "Dispositivo en línea",
            pl: "Device online",
            uk: "Пристрої онлайн",
            "zh-cn": "网上证人",
        },
        type: "boolean",
        role: "indicator.reachable",
        write: false,
        read: true,
        def: false,
        states: {
            false: "Offline",
            true: "Online",
        },
    },
    txbusy: {
        name: {
            en: "Busy",
            de: "Beschäftigt",
            ru: "Бой",
            pt: "Ocupado",
            nl: "Druk",
            fr: "Busy",
            it: "Occupato",
            es: "Ocupado",
            pl: "Busy",
            uk: "Автобуси",
            "zh-cn": "D. 布基亚",
        },
        type: "boolean",
        role: "indicator.working",
        write: false,
        read: true,
        def: false,
        states: {
            false: "no busy",
            true: "busy",
        },
    },
    name: {
        name: {
            en: "Name",
            de: "Name",
            ru: "Имя",
            pt: "Nome",
            nl: "Naam",
            fr: "Nom",
            it: "Nome",
            es: "Nombre",
            pl: "Nazwa",
            uk: "Ім'я",
            "zh-cn": "姓名",
        },
        type: "string",
        role: "info.name",
        write: true,
        read: true,
        def: "",
    },
    battery: {
        name: {
            en: "Battery level",
            de: "Batteriestand",
            ru: "Уровень батареи",
            pt: "Nível da bateria",
            nl: "Batterij niveau",
            fr: "Niveau de batterie",
            it: "Livello della batteria",
            es: "Nivel de batería",
            pl: "Bateria",
            uk: "Рівень акумулятора",
            "zh-cn": "B. 分配水平",
        },
        type: "number",
        role: "level.battery",
        write: false,
        read: true,
        def: 0,
        min: parseFloat("-9999"),
        max: 100,
        unit: "%",
    },
    batterylow: {
        name: {
            en: "Low Battery",
            de: "Niedrige Batterie",
            ru: "Низкая батарея",
            pt: "Baixa bateria",
            nl: "Law Battery",
            fr: "Batterie basse",
            it: "Batteria bassa",
            es: "Batería baja",
            pl: "Bateria Low",
            uk: "Низький акумулятор",
            "zh-cn": "低巴莱",
        },
        type: "boolean",
        role: "indicator.lowbat",
        write: false,
        read: true,
        def: false,
        states: {
            false: "low",
            true: "high",
        },
    },
    celsius: {
        name: {
            en: "Actual temperature for Alexa",
            de: "Aktuelle Temperatur für Alexa",
            ru: "Актуальная температура для Alexa",
            pt: "Temperatura real para Alexa",
            nl: "Actuele temperatuur voor Alexa",
            fr: "Température réelle pour Alexa",
            it: "Temperatura effettiva per Alexa",
            es: "Temperatura real para Alexa",
            pl: "Aktualna temperatura dla Alexy",
            uk: "Фактична температура для Alexa",
            "zh-cn": "Alexa的实际温度",
        },
        type: "number",
        role: "value.temperature",
        write: false,
        read: true,
        def: 0,
        min: parseFloat("-9999"),
        max: 3276.7,
        unit: "°C",
    },
    offset: {
        name: {
            en: "Offset",
            de: "Offset",
            ru: "Офсет",
            pt: "Desligado",
            nl: "Vertaling:",
            fr: "Offset",
            it: "Offset",
            es: "Offset",
            pl: "Offset",
            uk: "Оновити",
            "zh-cn": "B. 排 排 排",
        },
        type: "number",
        role: "info",
        write: false,
        read: true,
        def: 0,
        min: parseFloat("-9999"),
        max: 3276.7,
        unit: "°C",
    },
    tist: {
        name: {
            en: "Current  temperature",
            de: "Aktuelle Temperatur",
            ru: "Текущая температура",
            pt: "Temperatura atual",
            nl: "Current temperatuur",
            fr: "Température actuelle",
            it: "Temperatura attuale",
            es: "Temperatura actual",
            pl: "Temperatura bieżąca",
            uk: "Поточна температура",
            "zh-cn": "目前温度",
        },
        type: "number",
        role: "value.temperature",
        write: false,
        read: true,
        def: 0,
        min: parseFloat("-9999"),
        max: 3276.7,
        unit: "°C",
    },
    tsoll: {
        name: {
            en: "Target Temperature",
            de: "Zieltemperatur",
            ru: "Целевая температура",
            pt: "Temperatura de alvo",
            nl: "Target Temperature",
            fr: "Température cible",
            it: "Temperatura di destinazione",
            es: "Temperatura de destino",
            pl: "Target Temperatura",
            uk: "Цільова температура",
            "zh-cn": "目标图",
        },
        type: "number",
        role: "level.temperature",
        write: true,
        def: 0,
        min: parseFloat("-9999"),
        max: 3276.7,
        unit: "°C",
    },
    absenk: {
        name: {
            en: "Night temperature",
            de: "Nachttemperatur",
            ru: "Ночная температура",
            pt: "Temperatura da noite",
            nl: "Night temperatuur",
            fr: "Température nocturne",
            it: "Temperatura notturna",
            es: "Temperatura nocturna",
            pl: "Temperatura nocna",
            uk: "Нічна температура",
            "zh-cn": "温度",
        },
        type: "number",
        role: "info",
        write: false,
        read: true,
        def: 0,
        min: parseFloat("-9999"),
        max: 3276.7,
        unit: "°C",
    },
    komfort: {
        name: {
            en: "Comfort temperature",
            de: "Komforttemperatur",
            ru: "Температура комфорта",
            pt: "Temperatura de conforto",
            nl: "Comfort temperatuur",
            fr: "Température de confort",
            it: "Temperatura comfort",
            es: "Temperatura de confort",
            pl: "Temperatura Comforta",
            uk: "Погода",
            "zh-cn": "温度",
        },
        type: "number",
        role: "info",
        write: false,
        read: true,
        def: 0,
        min: parseFloat("-9999"),
        max: 3276.7,
        unit: "°C",
    },
    lock: {
        name: {
            en: "Lock",
            de: "Schließung",
            ru: "Блокировка",
            pt: "Bloqueio",
            nl: "Lock",
            fr: "Verrouillage",
            it: "Blocco",
            es: "Cerradura",
            pl: "Lock",
            uk: "Замки",
            "zh-cn": "Lock",
        },
        type: "boolean",
        role: "switch.lock",
        write: false,
        read: true,
        def: false,
        states: {
            false: "unlock",
            true: "lock",
        },
    },
    devicelock: {
        name: {
            en: "Device lock",
            de: "Geräteverriegelung",
            ru: "Устройство замок",
            pt: "Bloqueio de dispositivo",
            nl: "Device slot",
            fr: "Verrouillage du dispositif",
            it: "Blocco dispositivo",
            es: "Cierre de dispositivo",
            pl: "Umieszczenie",
            uk: "Блокування пристрою",
            "zh-cn": "目 录",
        },
        type: "boolean",
        role: "switch.lock",
        write: false,
        read: true,
        def: false,
        states: {
            false: "unlock",
            true: "lock",
        },
    },
    errorcode: {
        name: {
            en: "Error Code",
            de: "Fehlercode",
            ru: "Код ошибки",
            pt: "Código de erro",
            nl: "Error Code",
            fr: "Code d ' erreur",
            it: "Codice di errore",
            es: "Código de error",
            pl: "Kodeks Errowski",
            uk: "Код помилки",
            "zh-cn": "《逮捕法》",
        },
        type: "number",
        role: "info",
        write: false,
        read: true,
        def: 0,
        states: {
            0: "No Error",
            1: "No adaptation possible",
            2: "Battery power too weak",
            3: "No valve movement possible",
            4: "Installation ongoing",
            5: "Installation mode",
            6: "Adaptation of the heating valve",
        },
    },
    windowopenactiv: {
        name: {
            en: "Window open activ",
            de: "Fenster geöffnet",
            ru: "Окно открытый актив",
            pt: "Janela aberta activ",
            nl: "Window open activ",
            fr: "Window open activ",
            it: "Attivazione finestra aperta",
            es: "Ventana abierta activ",
            pl: "Otwieranie wiatru",
            uk: "Вікно відкритий актив",
            "zh-cn": "温得的公开活动",
        },
        type: "boolean",
        role: "switch.lock.window",
        write: true,
        read: true,
        def: false,
        states: {
            false: "close",
            true: "open",
        },
    },
    windowopenactiveendtime: {
        name: {
            en: "Actual time + Max. 24h - Value in Mintues",
            de: "Aktuelle Zeit + Max. 24h - Wert in Mintues",
            ru: "Актуальное время + Макс. 24h - Значение в минусах",
            pt: "Tempo real + Max. 24h - Valor em Mintues",
            nl: "Actuele tijd + Max 24h - Value in Mintuees",
            fr: "Temps réel + Max. 24h - Valeur en Mintues",
            it: "Ora attuale + Max. 24h - Valore in Mintues",
            es: "Hora actual + Max. 24h - Relación calidad/precio en Mintues",
            pl: "Czas działania + Max 24h - Value in Mintues (ang.)",
            uk: "Фактичний час + Max. 24h - Значення в Mintues",
            "zh-cn": "实际时间+24h-采矿价值",
        },
        type: "number",
        role: "value",
        write: true,
        read: true,
        def: 0,
    },
    boostactive: {
        name: {
            en: "Boost active",
            de: "Boost aktiv",
            ru: "Повышение активности",
            pt: "Impulsionar ativo",
            nl: "Boost actief",
            fr: "Boost active",
            it: "Miglioramento attivo",
            es: "Boost active",
            pl: "Aktywny",
            uk: "Активний",
            "zh-cn": "B. 积极活动",
        },
        type: "boolean",
        role: "switch.mode.boost",
        write: true,
        read: true,
        def: false,
        states: {
            false: "deactivated",
            true: "activated",
        },
    },
    boostactiveendtime: {
        name: {
            en: "Actual time + Max. 24h - Value in Mintues",
            de: "Aktuelle Zeit + Max. 24h - Wert in Mintues",
            ru: "Актуальное время + Макс. 24h - Значение в минусах",
            pt: "Tempo real + Max. 24h - Valor em Mintues",
            nl: "Actuele tijd + Max 24h - Value in Mintuees",
            fr: "Temps réel + Max. 24h - Valeur en Mintues",
            it: "Ora attuale + Max. 24h - Valore in Mintues",
            es: "Hora actual + Max. 24h - Relación calidad/precio en Mintues",
            pl: "Czas działania + Max 24h - Value in Mintues (ang.)",
            uk: "Фактичний час + Max. 24h - Значення в Mintues",
            "zh-cn": "实际时间+24h-采矿价值",
        },
        type: "number",
        role: "value",
        write: true,
        read: true,
        def: 0,
    },
    endperiod: {
        name: {
            en: "End period",
            de: "Endfrist",
            ru: "Конечный период",
            pt: "Período final",
            nl: "Einde periode",
            fr: "Période d ' achèvement",
            it: "Periodo di chiusura",
            es: "Período final",
            pl: "Koniec",
            uk: "Термін дії",
            "zh-cn": "结束期间",
        },
        type: "number",
        role: "value",
        write: false,
        read: true,
        def: 0,
    },
    tchange: {
        name: {
            en: "Next temperature change",
            de: "Nächste Temperaturänderung",
            ru: "Следующее изменение температуры",
            pt: "Alteração da próxima temperatura",
            nl: "De volgende temperatuur verandert",
            fr: "Changement de température",
            it: "Prossimo cambiamento di temperatura",
            es: "Cambio de temperatura siguiente",
            pl: "Zmiana temperatury",
            uk: "Зміна температури",
            "zh-cn": "今后温度变化",
        },
        type: "number",
        role: "value",
        write: false,
        read: true,
        def: 0,
        min: 0,
        max: 255,
    },
    devices: {
        name: {
            en: "Devices",
            de: "Geräte",
            ru: "Устройства",
            pt: "Dispositivos",
            nl: "Apparaten",
            fr: "Dispositifs",
            it: "Apparecchi",
            es: "Dispositivos",
            pl: "Urządzenia",
            uk: "Пристрої",
            "zh-cn": "设备",
        },
        type: "string",
        role: "json",
        write: false,
        read: true,
        def: "[]",
    },
    applymask: {
        name: {
            en: "Applymask",
            de: "Applymask",
            ru: "Applymask",
            pt: "Aplique a máscara",
            nl: "Toepassenmasker",
            fr: "Appliquer",
            it: "Applicaremask",
            es: "Applymask",
            pl: "Maska jabłkowa",
            uk: "Аптека",
            "zh-cn": "应用任务",
        },
        type: "string",
        role: "json",
        write: false,
        read: true,
        def: "[]",
    },
    sub_templates: {
        name: {
            en: "Sub templates",
            de: "Subvorlagen",
            ru: "Под шаблоны",
            pt: "Sub templates",
            nl: "Subsjablonen",
            fr: "Sous-modèles",
            it: "Sotto modelli",
            es: "Sub templates",
            pl: "Sub szablony",
            uk: "Шаблони",
            "zh-cn": "子模板",
        },
        type: "string",
        role: "json",
        write: false,
        read: true,
        def: "[]",
    },
    triggers: {
        name: {
            en: "Triggers",
            de: "Auslöser",
            ru: "Триггеры",
            pt: "Triggers",
            nl: "Trekkers",
            fr: "Déclencheurs",
            it: "Triggers",
            es: "Triggers",
            pl: "Przyczepy",
            uk: "Тригери",
            "zh-cn": "触发器",
        },
        type: "string",
        role: "json",
        write: false,
        read: true,
        def: "[]",
    },
    metadata: {
        name: {
            en: "Metadata",
            de: "Metadaten",
            ru: "Метаданные",
            pt: "Metadados",
            nl: "Metadata",
            fr: "Métadonnées",
            it: "Metadati",
            es: "Metadatos",
            pl: "Metadane",
            uk: "Метадані",
            "zh-cn": "元数据",
        },
        desc: "Metadata",
        icon: "img/metadata.png",
    },
    hkr_summer: {
        name: {
            en: "Summer time active",
            de: "Sommerzeit aktiv",
            ru: "Летнее время активно",
            pt: "Tempo de verão ativo",
            nl: "Zomertijd",
            fr: "Heure d ' été active",
            it: "Tempo estivo attivo",
            es: "Tiempo de verano activo",
            pl: "Czas letni",
            uk: "Активний літній час",
            "zh-cn": "积极时间",
        },
        type: "boolean",
        role: "switch.enable",
        write: false,
        read: true,
        def: false,
        states: {
            false: "deactivated",
            true: "activated",
        },
    },
    summeractive: {
        name: {
            en: "Summer time active",
            de: "Sommerzeit aktiv",
            ru: "Летнее время активно",
            pt: "Tempo de verão ativo",
            nl: "Zomertijd",
            fr: "Heure d ' été active",
            it: "Tempo estivo attivo",
            es: "Tiempo de verano activo",
            pl: "Czas letni",
            uk: "Активний літній час",
            "zh-cn": "积极时间",
        },
        type: "boolean",
        role: "switch.enable",
        write: false,
        read: true,
        def: false,
        states: {
            false: "deactivated",
            true: "activated",
        },
    },
    hkr_holidays: {
        name: {
            en: "Holiday active",
            de: "Urlaub aktiv",
            ru: "Праздник активный",
            pt: "Férias activas",
            nl: "Vakantie actief",
            fr: "Vacances actives",
            it: "Vacanza attiva",
            es: "Vacaciones activas",
            pl: "Świętowania",
            uk: "Активний відпочинок",
            "zh-cn": "积极活动",
        },
        type: "boolean",
        role: "info",
        write: false,
        read: true,
        def: false,
        states: {
            false: "deactivated",
            true: "activated",
        },
    },
    holidayactive: {
        name: {
            en: "Holiday active",
            de: "Urlaub aktiv",
            ru: "Праздник активный",
            pt: "Férias activas",
            nl: "Vakantie actief",
            fr: "Vacances actives",
            it: "Vacanza attiva",
            es: "Vacaciones activas",
            pl: "Świętowania",
            uk: "Активний відпочинок",
            "zh-cn": "积极活动",
        },
        type: "boolean",
        role: "info",
        write: false,
        read: true,
        def: false,
        states: {
            false: "deactivated",
            true: "activated",
        },
    },
    state: {
        name: {
            en: "state",
            de: "Zustand",
            ru: "государство",
            pt: "estado",
            nl: "staat",
            fr: "état",
            it: "stato",
            es: "estado",
            pl: "państwo stanowe",
            uk: "стан",
            "zh-cn": "州",
        },
        type: "boolean",
        role: "switch",
        write: true,
        read: true,
        def: false,
        states: {
            false: "off",
            true: "on",
        },
    },
    alertstate: {
        name: {
            en: "state",
            de: "Zustand",
            ru: "государство",
            pt: "estado",
            nl: "staat",
            fr: "état",
            it: "stato",
            es: "estado",
            pl: "państwo stanowe",
            uk: "стан",
            "zh-cn": "州",
        },
        type: "number",
        role: "state",
        write: false,
        read: true,
        def: 0,
        states: { 0: "Kein Fehler", 1: "Hindernisalarm", 2: "Überhitzungsalarm" },
    },
    simpleonoff: {
        name: {
            en: "state",
            de: "Zustand",
            ru: "государство",
            pt: "estado",
            nl: "staat",
            fr: "état",
            it: "stato",
            es: "estado",
            pl: "państwo stanowe",
            uk: "стан",
            "zh-cn": "州",
        },
        type: "number",
        role: "value",
        write: true,
        read: true,
        def: 0,
        states: { 0: "off", 1: "on", 2: "toggle" },
    },
    blindstate: {
        name: {
            en: "Alarm",
            de: "Alarmstufe",
            ru: "Сигнализация",
            pt: "Alarme de alarme",
            nl: "Alarm",
            fr: "Alarme",
            it: "Allarme",
            es: "Alarma",
            pl: "Alarma",
            uk: "Напильник",
            "zh-cn": "Alarm",
        },
        type: "number",
        role: "sensor.window",
        write: false,
        read: true,
        def: 0,
        states: { 0: "No Error", 1: "Obstacle alarm", 2: "Overheat alarm" },
    },
    mode: {
        name: {
            en: "Mode",
            de: "Modus",
            ru: "Режим",
            pt: "Modo",
            nl: "Mode",
            fr: "Mode",
            it: "Modalità",
            es: "Modo",
            pl: "Mode Mode Mode",
            uk: "Режим",
            "zh-cn": "导 言",
        },
        type: "string",
        role: "info",
        write: false,
        read: true,
        def: "manuell",
        states: { manuell: "manuell", auto: "automatic" },
    },
    voltage: {
        name: {
            en: "Voltage",
            de: "Spannung",
            ru: "Напряжение",
            pt: "Tensão",
            nl: "Voltage",
            fr: "Tension",
            it: "Tensione",
            es: "Voltaje",
            pl: "Voltage",
            uk: "Навігація",
            "zh-cn": "动产",
        },
        type: "number",
        role: "value.voltage",
        write: false,
        read: true,
        def: 0,
        unit: "V",
    },
    power: {
        name: {
            en: "Power",
            de: "Leistung",
            ru: "Сила",
            pt: "Poder",
            nl: "Power",
            fr: "Puissance",
            it: "Potenza",
            es: "Poder",
            pl: "Power Power Power",
            uk: "Потужність",
            "zh-cn": "管理国",
        },
        type: "number",
        role: "value.power",
        write: false,
        read: true,
        def: 0,
        unit: "W",
    },
    hex: {
        name: {
            en: "HEX",
            de: "HEX",
            ru: "HEX",
            pt: "HEX",
            nl: "HEX",
            fr: "HEX",
            it: "HEX",
            es: "HEX",
            pl: "HEX",
            uk: "ХЕКС",
            "zh-cn": "美国",
        },
        type: "string",
        role: "level.color.rgb",
        write: true,
        read: true,
        def: "#ff4a50",
        states: {
            "#000000": "off",
            "#ff4a50": "red outer circle",
            "#cc7275": "red center circle",
            "#9c7b7c": "red inner circle",
            "#ffa629": "orange outer circle",
            "#e0ad65": "orange center circle",
            "#ccb493": "orange inner circle",
            "#ffeb66": "yellow outer circle",
            "#e0d487": "yellow center circle",
            "#ccc7a3": "yellow inner circle",
            "#beff85": "lime outer circle",
            "#bbe09b": "lime center circle",
            "#bcccad": "lime inner circle",
            "#5eff5e": "green outer circle",
            "#8bcc8b": "green center circle",
            "#849c84": "green inner circle",
            "#6effcf": "turquoise outer circle",
            "#89ccb6": "turquoise center circle",
            "#839c93": "turquoise inner circle",
            "#4dd2ff": "cyan outer circle",
            "#6eb5cc": "cyan center circle",
            "#78939c": "cyan inner circle",
            "#57a5ff": "lightblue outer circle",
            "#749dcc": "lightblue center circle",
            "#79899c": "lightblue inner circle",
            "#3366ff": "blue outer circle",
            "#607bcc": "blue center circle",
            "#737d9c": "blue inner circle",
            "#a057ff": "purple outer circle",
            "#9a74cc": "purple center circle",
            "#897b9c": "purple inner circle",
            "#f673ff": "magenta outer circle",
            "#c783cc": "magenta center circle",
            "#9a809c": "magenta inner circle",
            "#ff4a95": "pink outer circle",
            "#cc769a": "pink center circle",
            "#9c7c89": "pink inner circle",
        },
    },
    energy: {
        name: {
            en: "Energy",
            de: "Energie",
            ru: "Энергия",
            pt: "Energia",
            nl: "Energie",
            fr: "Énergie",
            it: "Energia",
            es: "Energy",
            pl: "Energia",
            uk: "Енергетика",
            "zh-cn": "能源",
        },
        type: "number",
        role: "value.energy",
        write: false,
        read: true,
        def: 0,
        unit: "Wh",
    },
    lastpressedtimestamp: {
        name: {
            en: "Last pressed timestamp",
            de: "Letzter gepresster Zeitstempel",
            ru: "Последний прессованный timetamp",
            pt: "Last pressionado timestamp",
            nl: "Laatste drukke tijden",
            fr: "Last pressed timestamp",
            it: "Ultimo timestamp pressato",
            es: "Último temporizador prensado",
            pl: "Ostateczny znaczek czasowy",
            uk: "Останній пресований час",
            "zh-cn": "最后新闻稿",
        },
        type: "number",
        role: "value",
        write: false,
        read: true,
        def: 0,
    },

    etsideviceid: {
        name: {
            en: "Internal device ID",
            de: "Interne Geräte-ID",
            ru: "Внутреннее устройство ID",
            pt: "ID do dispositivo interno",
            nl: "Internal device ID",
            fr: "ID du dispositif interne",
            it: "ID dispositivo interno",
            es: "ID del dispositivo interno",
            pl: "Urządzenia wewnętrzne",
            uk: "Внутрішній пристрій ID",
            "zh-cn": "内部装置",
        },
        type: "number",
        role: "info",
        write: false,
        read: true,
        def: 0,
    },
    unittype: {
        name: {
            en: "Unit type",
            de: "Typ der Einheit",
            ru: "Тип единицы",
            pt: "Tipo de unidade",
            nl: "Eenheid type",
            fr: "Type d ' unité",
            it: "Tipo di unità",
            es: "Tipo de unidad",
            pl: "Typ maszynowy",
            uk: "Тип агрегату",
            "zh-cn": "单位类型",
        },
        type: "number",
        role: "info",
        write: false,
        read: true,
        def: 0,
        states: {
            0: "Unknwon",
            273: "SIMPLE_BUTTON",
            256: "SIMPLE_ON_OFF_SWITCHABLE",
            257: "SIMPLE_ON_OFF_SWITCH",
            262: "AC_OUTLET",
            263: "AC_OUTLET_SIMPLE_POWER_METERING",
            264: "SIMPLE_LIGHT",
            265: "DIMMABLE_LIGHT",
            266: "DIMMER_SWITCH",
            277: "COLOR_BULB",
            278: "DIMMABLE_COLOR_BULB",
            281: "BLIND",
            282: "LAMELLAR",
            512: "SIMPLE_DETECTOR",
            513: "DOOR_OPEN_CLOSE_DETECTOR",
            514: "WINDOW_OPEN_CLOSE_DETECTOR",
            515: "MOTION_DETECTOR",
            518: "FLOOD_DETECTOR",
            519: "GLAS_BREAK_DETECTOR",
            520: "VIBRATION_DETECTOR",
            640: "SIREN",
        },
    },
    interfaces: {
        name: {
            en: "Interfaces",
            de: "Schnittstellen",
            ru: "Интерфейсы",
            pt: "Interfaces",
            nl: "Vertaling:",
            fr: "Interfaces",
            it: "Interfacce",
            es: "Interfaces",
            pl: "Interface",
            uk: "Інтерфейси",
            "zh-cn": "接口",
        },
        type: "string",
        role: "info",
        write: false,
        read: true,
        def: "",
    },
    lastalertchgtimestamp: {
        name: {
            en: "Last alert timestamp",
            de: "Letzte Alarmzeitstempel",
            ru: "Последние оповещения timetamp",
            pt: "Última hora de alerta",
            nl: "Laatste waarschuwingstijd",
            fr: "Dernière alerte timestamp",
            it: "Ultimo avviso timestamp",
            es: "Última hora de alerta",
            pl: "Last Timestamp",
            uk: "Останнє повідомлення",
            "zh-cn": "上一次警戒时间",
        },
        type: "number",
        role: "value",
        write: false,
        read: true,
        def: 0,
    },
    level: {
        name: {
            en: "Level 0(0%) - 255(100%)",
            de: "Ebene 0(0%) - 255(100%)",
            ru: "Уровень 0(0%) - 255(100%)",
            pt: "Nível 0(0%) - 255(100%)",
            nl: "Niveau 0 (0%) - 255 (100%)",
            fr: "Niveau 0(0%) - 255(100%)",
            it: "Livello 0 (0%) - 255 (100%)",
            es: "Nivel 0(0%) - 255(100%)",
            pl: "Poziom 0 (0%) - 255(100%) ",
            uk: "Рівень 0(0%) - 255(100%)",
            "zh-cn": "职等0.(0%) - 255(100%)",
        },
        type: "number",
        role: "value.level",
        write: true,
        read: true,
        def: 0,
        min: 0,
        max: 255,
    },
    levelpercentage: {
        name: {
            en: "Level percentage 0-100",
            de: "Niveauprozent 0-100",
            ru: "Процент уровня 0-100",
            pt: "Percentagem de nível 0-100",
            nl: "Niveau percentage 0-100",
            fr: "Pourcentage de niveau 0-100",
            it: "Percentuale di livello 0-100",
            es: "Porcentaje de nivel 0-100",
            pl: "Poziomy",
            uk: "Відсоток рівня 0-100",
            "zh-cn": "百分比",
        },
        type: "number",
        role: "level.dimmer",
        write: true,
        read: true,
        def: 0,
        min: 0,
        max: 100,
        unit: "%",
    },
    supported_modes: {
        name: {
            en: "Supported modes",
            de: "Unterstützte Modi",
            ru: "Поддерживаемые режимы",
            pt: "Modos suportados",
            nl: "Ondersteuning",
            fr: "Modes supportés",
            it: "Modalità supportate",
            es: "Modos compatibles",
            pl: "Tryb wsparcia",
            uk: "Підтримувані режими",
            "zh-cn": "支助模式",
        },
        type: "number",
        role: "info",
        write: false,
        read: true,
        def: 0,
        states: { "-1": "unknown", 2: "Hue Saturation-Mode", 5: "Color temperature mode" },
    },
    current_mode: {
        name: {
            en: "Current mode",
            de: "Aktueller Modus",
            ru: "Текущий режим",
            pt: "Modo atual",
            nl: "Current Mode",
            fr: "Mode actuel",
            it: "Modalità attuale",
            es: "Modo actual",
            pl: "Tryb bieżący",
            uk: "Поточний режим",
            "zh-cn": "当前模式",
        },
        type: "number",
        role: "info",
        write: false,
        read: true,
        def: 0,
        states: { 0: "unknown", 1: "Hue Saturation", 4: "Color temperature" },
    },
    fullcolorsupport: {
        name: {
            en: "Full color support",
            de: "Volle Farbunterstützung",
            ru: "Полная поддержка цвета",
            pt: "Suporte de cor completa",
            nl: "Volle kleuren ondersteuning",
            fr: "Support couleur complet",
            it: "Supporto a colori completo",
            es: "Soporte completo de color",
            pl: "Obsługa koloru",
            uk: "Повна підтримка кольору",
            "zh-cn": "全力支持",
        },
        type: "boolean",
        role: "info",
        write: false,
        read: true,
        def: false,
        states: {
            false: "no",
            true: "yes",
        },
    },
    mapped: {
        name: {
            en: "Mapped",
            de: "Karten",
            ru: "Карта",
            pt: "Maculada",
            nl: "Mapped",
            fr: "Mapped",
            it: "Mappa",
            es: "Mapped",
            pl: "Okładka",
            uk: "Мапа",
            "zh-cn": "毛里求斯",
        },
        type: "boolean",
        role: "info",
        write: false,
        read: true,
        def: false,
        states: {
            false: "no",
            true: "yes",
        },
    },
    saturation: {
        name: {
            en: "Saturation (0-255)",
            de: "Sättigung (0-255)",
            ru: "Сатурация (0-255)",
            pt: "Saturação (0-255)",
            nl: "Saturatie (0-255)",
            fr: "Saturation (0-255)",
            it: "Saturazione (0-255)",
            es: "Saturación (0-255)",
            pl: "Saturacja (0-255)",
            uk: "Зберегти (0-255)",
            "zh-cn": "饱 质 (0-255)",
        },
        type: "number",
        role: "level.color.saturation",
        write: true,
        read: true,
        def: -1,
        min: -1,
        max: 255,
    },
    unmapped_hue: {
        name: {
            en: "Unmapped hue (0-359)",
            de: "Unmaped hue (0-359)",
            ru: "Незамеченное место (0-359)",
            pt: "Abraço sem costura (0-359)",
            nl: "Unmap hue (0-359)",
            fr: "Coque non plaquée (0-359)",
            it: "Scadenza (0-359)",
            es: "Hueca no cubierta (0-359)",
            pl: "Unmapped hue (0-359)",
            uk: "Незрівняний відтінок (0-359)",
            "zh-cn": "无人驾驶员 (0-359)",
        },
        type: "number",
        role: "info",
        write: true,
        read: true,
        def: -1,
        min: -1,
        max: 359,
        unit: "°",
    },
    unmapped_saturation: {
        name: {
            en: "Unmapped saturation (0-255)",
            de: "Unübersichtliche Sättigung (0-255)",
            ru: "Безналичная насыщенность (0-255)",
            pt: "Saturação desmatada (0-255)",
            nl: "Onaangepaste saturatie (0-255)",
            fr: "Saturation non plafonnée (0-255)",
            it: "Saturazione non mappata (0-255)",
            es: "Saturación no cubierta (0-255)",
            pl: "Nasycenie niesamowite (0-255)",
            uk: "Незрівняне насичення (0-255)",
            "zh-cn": "A. 未支配性 (0-255)",
        },
        type: "number",
        role: "info",
        write: true,
        read: true,
        def: -1,
        min: -1,
        max: 255,
    },
    hkr_temperature: {
        name: {
            en: "Temperature",
            de: "Temperatur",
            ru: "Температура",
            pt: "Temperatura",
            nl: "Temperatuur",
            fr: "Température",
            it: "Temperatura",
            es: "Temperatura",
            pl: "Temperatura",
            uk: "Погода",
            "zh-cn": "模范",
        },
        type: "number",
        role: "level.color.temperature",
        write: true,
        read: true,
        def: -1,
        min: -1,
        max: 6500,
        unit: "K",
        states: {
            "-1": "Off",
            2700: "Warm white_1",
            3000: "Warm white_2",
            3400: "Warm white_3",
            3800: "Neutral white_1",
            4200: "Neutral white_2",
            4700: "Neutral white_3",
            5300: "Daylight_1",
            5900: "Daylight_1",
            6500: "Daylight_1",
        },
    },
    temperature: {
        name: {
            en: "Temperature",
            de: "Temperatur",
            ru: "Температура",
            pt: "Temperatura",
            nl: "Temperatuur",
            fr: "Température",
            it: "Temperatura",
            es: "Temperatura",
            pl: "Temperatura",
            uk: "Погода",
            "zh-cn": "模范",
        },
        type: "number",
        role: "level.color.temperature",
        write: true,
        read: true,
        def: -1,
        min: -1,
        max: 6500,
        unit: "K",
        states: {
            "-1": "Off",
            2700: "Warm white_1",
            3000: "Warm white_2",
            3400: "Warm white_3",
            3800: "Neutral white_1",
            4200: "Neutral white_2",
            4700: "Neutral white_3",
            5300: "Daylight_1",
            5900: "Daylight_1",
            6500: "Daylight_1",
        },
    },
    endpositionsset: {
        name: {
            en: "End position",
            de: "Endposition",
            ru: "Конечная позиция",
            pt: "Posição final",
            nl: "Einde positie",
            fr: "Position finale",
            it: "Posizione finale",
            es: "Posición final",
            pl: "Pozycja końcowa",
            uk: "Кінцева позиція",
            "zh-cn": "结束立场",
        },
        type: "number",
        role: "info",
        write: false,
        read: true,
        def: -1,
        states: {
            "-1": "unknown",
            0: "nicht konifiguriert",
            1: "konifiguriert",
        },
    },
    hue: {
        name: {
            en: "Hue value in degrees (0-359)",
            de: "Hue-Wert in Grad (0-359)",
            ru: "Огромное значение в градусах (0-359)",
            pt: "Valor Hue em graus (0-359)",
            nl: "Hue waarde in graad (0-359)",
            fr: "Valeur en degrés 0-359",
            it: "Valore di usura in gradi (0-359)",
            es: "Valor de Hueso en grados (0-359)",
            pl: "Wartość w stopniach (0-359)",
            uk: "Значення Hue в градусах (0-359)",
            "zh-cn": "度值 (0-359)",
        },
        type: "number",
        role: "level.color.hue",
        write: true,
        read: true,
        def: -1,
        min: -1,
        max: 359,
        unit: "°",
    },
    masterdeviceid: {
        name: {
            en: "Interne ID",
            de: "Interner ID",
            ru: "Интерне ID",
            pt: "ID Interne",
            nl: "ID",
            fr: "Interne ID",
            it: "ID Interno",
            es: "ID de interne",
            pl: "Interne ID",
            uk: "Інтернешнл ID",
            "zh-cn": "国际发展部",
        },
        type: "number",
        role: "info",
        write: false,
        read: true,
        def: 0,
    },
    members: {
        name: {
            en: "Group member IDs",
            de: "Gruppenmitglieder IDs",
            ru: "Член группы IDs",
            pt: "IDs de membros do grupo",
            nl: "Groepslid ID",
            fr: "ID membres du groupe",
            it: "ID dei membri del gruppo",
            es: "IDs de miembro del grupo",
            pl: "Członek grupy ID",
            uk: "Коди учасників групи",
            "zh-cn": "集团成员",
        },
        type: "string",
        role: "info",
        write: true,
        read: true,
        def: "0",
    },
    humidity: {
        name: {
            en: "Relative Humidity",
            de: "Relative Luftfeuchtigkeit",
            ru: "Относительная влажность",
            pt: "Humidade relativa",
            nl: "Relatieve Humid",
            fr: "Humidité relative",
            it: "Umidità relativa",
            es: "Humedad relativa",
            pl: "Stosunkowość",
            uk: "Відносна вологість",
            "zh-cn": "相对的创伤",
        },
        type: "number",
        role: "value.humidity",
        write: false,
        read: true,
        def: -1,
        min: -1,
        max: 100,
        unit: "%",
    },
    rel_humidity: {
        name: {
            en: "Humidity",
            de: "Luftfeuchtigkeit",
            ru: "Влажность",
            pt: "Humidade",
            nl: "Humid",
            fr: "Humidité",
            it: "Umidità",
            es: "Humedad",
            pl: "Humity",
            uk: "Вологість",
            "zh-cn": "死 情",
        },
        type: "number",
        role: "value.humidity",
        write: false,
        read: true,
        def: -1,
        min: -1,
        max: 100,
        unit: "%",
    },
    synchronized: {
        name: {
            en: "synchronized",
            de: "synchronisiert",
            ru: "синхронизировано",
            pt: "sincronizado",
            nl: "synchronized",
            fr: "synchronisé",
            it: "sincronizzazione",
            es: "sincronizado",
            pl: "synchronizować",
            uk: "синхронізований",
            "zh-cn": "同步",
        },
        type: "boolean",
        role: "info",
        write: false,
        read: true,
        def: false,
        states: {
            false: "no",
            true: "yes",
        },
    },
    autocreate: {
        name: {
            en: "Created automatic",
            de: "Automatische Erstellung",
            ru: "Создана автоматическая",
            pt: "Criado automático",
            nl: "Gecreëerd automatisch",
            fr: "Création automatique",
            it: "Creato automatico",
            es: "Creado automático",
            pl: "Automatyczna tworzenie",
            uk: "Створено автоматичне",
            "zh-cn": "自动创建",
        },
        type: "boolean",
        role: "info",
        write: false,
        read: true,
        def: false,
        states: {
            false: "no",
            true: "yes",
        },
    },
    active: {
        name: {
            en: "Active",
            de: "Aktiv",
            ru: "Активно",
            pt: "Activo",
            nl: "Active",
            fr: "Active",
            it: "Attivo",
            es: "Activo",
            pl: "Aktywny",
            uk: "Активний",
            "zh-cn": "精算师",
        },
        type: "boolean",
        role: "info",
        write: true,
        read: true,
        def: false,
        states: {
            false: "no",
            true: "yes",
        },
    },
    relay_manual: {
        name: {
            en: "Switchable socket/lamp/actuator ON/OFF",
            de: "Schaltdose/Lampe/Aktuator ON/OFF",
            ru: "Переключаемый розетка/ламп/актуатор ON/OFF",
            pt: "Soquete/lamp/actuador comutável ON/OFF",
            nl: "Switchable socket/lamp/actuator ON/OFF",
            fr: "Douille/lampe/actionneur commutable ON/OFF",
            it: "Presa commutabile/lamp/actuatore ON/OFF",
            es: "Enchufe/lamp/accionador conmutable ON/OFF",
            pl: "Switchable socket/lamp/actuator",
            uk: "Вимкнений роз'єм / підсилювач / пристрій ON / Off",
            "zh-cn": "刚果/森林论坛",
        },
        type: "boolean",
        role: "switch",
        write: false,
        read: true,
        def: false,
        states: {
            false: "off",
            true: "on",
        },
    },
    relay_automatic: {
        name: {
            en: "On/off switchable socket/lamp/roller shutter timer switch",
            de: "Ein/Aus schaltbare Steckdose/Lampe/Rolle Schaltuhr",
            ru: "On/off переключаемый socket/lamp/roller выключатель времени",
            pt: "Interruptor do temporizador do obturador/lobo/rolo do interruptor do obturador",
            nl: "On-off wisselbare socket/lamp/roller sluitertijdschakelaar",
            fr: "Interrupteur d ' arrêt de la prise/de la lampe/de la commande",
            it: "Interruttore di temporizzazione dell'otturatore dell'interruttore di accensione/spegnimento",
            es: "Interruptor de tiempo de obturador de toma/lamp/rollador conmutable de encendido/ apagado",
            pl: "Na/off switchable/lamp/roll shutter time switcher",
            uk: "Перемикач вимикача / роз'єм / вимикач",
            "zh-cn": "转换/转用可变的单件/移动/推销时间",
        },
        type: "boolean",
        role: "switch",
        write: false,
        read: true,
        def: false,
        states: {
            false: "off",
            true: "on",
        },
    },
    main_wifi: {
        name: {
            en: "WLAN on/off",
            de: "WLAN an/aus",
            ru: "WLAN на/выкл",
            pt: "WLAN ligar/desligar",
            nl: "WLAN on/off",
            fr: "WLAN on/off",
            it: "WLAN on/off",
            es: "WLAN on/off",
            pl: "WLAN na/off",
            uk: "ВЛАСТИВОСТІ",
            "zh-cn": "WLAN on/off",
        },
        type: "boolean",
        role: "switch",
        write: false,
        read: true,
        def: false,
        states: {
            false: "off",
            true: "on",
        },
    },
    guest_wifi: {
        name: {
            en: "Guest WLAN on/off",
            de: "Gäste-WLAN an/aus",
            ru: "Гость WLAN on/off",
            pt: "WLAN de convidado ligado / desligado",
            nl: "Guest WLAN op",
            fr: "WLAN invité/off",
            it: "Ospiti WLAN on/off",
            es: "Guest WLAN on/off",
            pl: "Guest WLAN (ang.)",
            uk: "Гість WLAN на / з",
            "zh-cn": "Gest WLAN on/off",
        },
        type: "boolean",
        role: "switch",
        write: false,
        read: true,
        def: false,
        states: {
            false: "off",
            true: "on",
        },
    },
    tam_control: {
        name: {
            en: "Answering machine on/off",
            de: "Antwortmaschine auf/ab",
            ru: "Отвечая машина на/выключение",
            pt: "Máquina de resposta on/off",
            nl: "Antwoordmachine aan/off",
            fr: "Machine de réponse sur/off",
            it: "Rispondendo alla macchina",
            es: "Máquina de respuesta en / apagado",
            pl: "Maszyna dotycząca na/offer",
            uk: "Відповідача машини/відправлення",
            "zh-cn": "对/投机",
        },
        type: "boolean",
        role: "switch",
        write: false,
        read: true,
        def: false,
        states: {
            false: "off",
            true: "on",
        },
    },
    mask: {
        name: {
            en: "apply mask",
            de: "auf anfrage",
            ru: "применить маску",
            pt: "aplicar máscara",
            nl: "masker",
            fr: "masque",
            it: "applicare la maschera",
            es: "aplicar máscara",
            pl: "maska",
            uk: "маска для нанесення",
            "zh-cn": "适用的单位",
        },
        type: "number",
        role: "info",
        write: false,
        read: true,
        def: 0,
    },
    adaptiveHeatingActive: {
        name: {
            en: "Heating control activated",
            de: "Heizungssteuerung aktiviert",
            ru: "Нагревательный контроль активирован",
            pt: "Controle de aquecimento ativado",
            nl: "Verhittingscontrole geactiveerd",
            fr: "Commande de chauffage activé",
            it: "Controllo riscaldamento attivato",
            es: "Control de calefacción activado",
            pl: "Aktywowany",
            uk: "Нагрівальний контроль активоване",
            "zh-cn": "控制活动",
        },
        type: "boolean",
        role: "info",
        write: false,
        read: true,
        def: false,
        states: {
            false: "no",
            true: "yes",
        },
    },
    apply_template: {
        name: {
            en: "apply this template",
            de: "Diese Vorlage anwenden",
            ru: "применить этот шаблон",
            pt: "aplicar este modelo",
            nl: "apply this template",
            fr: "appliquer ce modèle",
            it: "applicare questo modello",
            es: "aplicar esta plantilla",
            pl: "stosować ten szablon",
            uk: "застосувати цей шаблон",
            "zh-cn": "采用这一模板",
        },
        type: "boolean",
        role: "button",
        write: true,
        read: true,
        def: false,
    },
    adaptiveHeatingRunning: {
        name: {
            en: "The adaptive heating control is currently heating",
            de: "Die adaptive Heizsteuerung ist derzeit Heizung",
            ru: "Адаптивный контроль отопления в настоящее время нагревается",
            pt: "O controlo de aquecimento adaptativo está actualmente a aquecer",
            nl: "De aanpassingscontrole is nu verhit",
            fr: "La commande de chauffage adaptative est actuellement en chauffage",
            it: "Il controllo del riscaldamento adattivo è attualmente il riscaldamento",
            es: "El control de calefacción adaptativo es actualmente calefacción",
            pl: "Przetwarzanie ciepła adaptacyjnego jest obecnie ogrzewane",
            uk: "В даний час нагрівається адаптивне опалення",
            "zh-cn": "调整后的控制目前正在进行。",
        },
        type: "boolean",
        role: "info",
        write: false,
        read: true,
        def: false,
        states: {
            false: "no",
            true: "yes",
        },
    },
    type: {
        name: {
            en: "Type",
            de: "Art",
            ru: "Тип",
            pt: "Tipo",
            nl: "Type",
            fr: "Type",
            it: "Tipo",
            es: "Tipo",
            pl: "Typ",
            uk: "Тип",
            "zh-cn": "类型",
        },
        type: "string",
        role: "info",
        write: true,
        read: true,
        def: "generic",
        states: ["no set", "coming", "leaving", "generic"],
    },
    icon: {
        name: {
            en: "Icon",
            de: "Icon",
            ru: "Икона",
            pt: "Ícone",
            nl: "Icon",
            fr: "Icon",
            it: "Icona",
            es: "Icon",
            pl: "Ikon",
            uk: "Ікона",
            "zh-cn": "一. 导言",
        },
        type: "number",
        role: "info",
        write: true,
        read: true,
        def: 0,
    },
    setMetadata: {
        name: {
            en: "Set metadata",
            de: "Metadaten setzen",
            ru: "Набор метаданных",
            pt: "Definir metadados",
            nl: "Metadata instellen",
            fr: "Définir les métadonnées",
            it: "Set metadati",
            es: "Establecer metadatos",
            pl: "Ustaw metadane",
            uk: "Налаштування метаданих",
            "zh-cn": "设置元数据",
        },
        type: "boolean",
        role: "button",
        write: true,
        read: true,
        def: false,
    },
    dialhelper: {
        name: {
            en: "dial helper",
            de: "zifferblatt helfer",
            ru: "диальный помощник",
            pt: "auxiliar de discagem",
            nl: "dial helper",
            fr: "composer l'aideur",
            it: "dial helper",
            es: "marcar ayudante",
            pl: "pomocnik",
            uk: "щоденний помічник",
            "zh-cn": "求助者",
        },
        type: "string",
        role: "state",
        write: false,
        read: true,
        def: "",
    },
    custom_notification: {
        name: {
            en: "custom notification",
            de: "benutzerdefinierte Benachrichtigung",
            ru: "пользовательское уведомление",
            pt: "notificação personalizada",
            nl: "custom notification",
            fr: "notification personnalisée",
            it: "notifica personalizzata",
            es: "notificación personalizada",
            pl: "notacja",
            uk: "користувацькі повідомлення",
            "zh-cn": "习惯通知",
        },
        type: "string",
        role: "state",
        write: false,
        read: true,
        def: "",
    },
    hkr_time_table: {
        name: {
            en: "time table",
            de: "Zeittabelle",
            ru: "таблица времени",
            pt: "tabela de tempo",
            nl: "time table",
            fr: "time table",
            it: "tabella di tempo",
            es: "tiempo",
            pl: "tabela czasu",
            uk: "таблиця часу",
            "zh-cn": "时间表",
        },
        type: "string",
        role: "state",
        write: false,
        read: true,
        def: "",
    },
    http_request: {
        name: {
            en: "HTTP request",
            de: "HTTP-Anforderung",
            ru: "HTTP запрос",
            pt: "Pedido HTTP",
            nl: "HTP verzoek",
            fr: "Requête HTTP",
            it: "Richiesta HTTP",
            es: "HTTP request",
            pl: "Żądanie HTTP",
            uk: "HTTP запит",
            "zh-cn": "HTTP请求",
        },
        type: "string",
        role: "state",
        write: false,
        read: true,
        def: "",
    },
    blindstop: {
        name: {
            en: "shutters stop",
            de: "Rolllade Stopp",
            ru: "затворы остановки",
            pt: "parada de persiana",
            nl: "shutters stop",
            fr: "shutters stop",
            it: "tapparelle",
            es: "persianas paran",
            pl: "przystanek zatrzymuje się",
            uk: "стопи",
            "zh-cn": "关闭",
        },
        type: "boolean",
        role: "button.stop",
        write: true,
        read: true,
        def: false,
    },
    blindopen: {
        name: {
            en: "shutters open",
            de: "Rolllade öffnen",
            ru: "затворы открыты",
            pt: "portas abertas",
            nl: "kappen open",
            fr: "volets ouverts",
            it: "persiane aperte",
            es: "persianas abiertas",
            pl: "otwierać",
            uk: "відкриті двері",
            "zh-cn": "开 门",
        },
        type: "boolean",
        role: "button.open.blind",
        write: true,
        read: true,
        def: false,
    },
    blindclose: {
        name: {
            en: "shutters close",
            de: "Rolllade schließen",
            ru: "затворы закрываются",
            pt: "persianas perto",
            nl: "shutters sluit",
            fr: "volets fermés",
            it: "chiudi le persiane",
            es: "persianas cerradas",
            pl: "zamknąć",
            uk: "закрити",
            "zh-cn": "关闭",
        },
        type: "boolean",
        role: "button.close.blind",
        write: true,
        read: true,
        def: false,
    },
    blindlevel: {
        name: {
            en: "Level percentage 0-100",
            de: "Niveauprozent 0-100",
            ru: "Процент уровня 0-100",
            pt: "Percentagem de nível 0-100",
            nl: "Niveau percentage 0-100",
            fr: "Pourcentage de niveau 0-100",
            it: "Percentuale di livello 0-100",
            es: "Porcentaje de nivel 0-100",
            pl: "Poziomy",
            uk: "Відсоток рівня 0-100",
            "zh-cn": "百分比",
        },
        type: "number",
        role: "level.blind",
        write: true,
        read: true,
        def: 0,
        min: 0,
        max: 100,
        unit: "%",
    },
    blindvalue: {
        name: {
            en: "Level percentage 0-100",
            de: "Niveauprozent 0-100",
            ru: "Процент уровня 0-100",
            pt: "Percentagem de nível 0-100",
            nl: "Niveau percentage 0-100",
            fr: "Pourcentage de niveau 0-100",
            it: "Percentuale di livello 0-100",
            es: "Porcentaje de nivel 0-100",
            pl: "Poziomy",
            uk: "Відсоток рівня 0-100",
            "zh-cn": "百分比",
        },
        type: "number",
        role: "value.blind",
        write: true,
        read: true,
        def: 0,
        min: 0,
        max: 100,
        unit: "%",
    },
    stateonoff: {
        name: {
            en: "Light switch",
            de: "Lichtschalter",
            ru: "Световой переключатель",
            pt: "Interruptor de luz",
            nl: "Licht",
            fr: "Interrupteur de lumière",
            it: "Interruttore di luce",
            es: "Interruptor de luz",
            pl: "Light switch",
            uk: "Вимикач світла",
            "zh-cn": "B. 照明的转换",
        },
        type: "boolean",
        role: "switch.light",
        write: true,
        read: true,
        def: false,
        states: {
            false: "off",
            true: "on",
        },
    },
    getTemperatureStatistic: {
        name: {
            en: "Temperature statistic",
            de: "Temperaturstatistik",
            ru: "Статистика температуры",
            pt: "Estatística de temperatura",
            nl: "Temperatuur statistiek",
            fr: "Statistiques de la température",
            it: "Temperatura statistica",
            es: "Estadística de temperatura",
            pl: "Statystyki Temperatury",
            uk: "Статистика температури",
            "zh-cn": "统计",
        },
        type: "boolean",
        role: "button",
        write: true,
        read: true,
        def: false,
    },
    getColor: {
        name: {
            en: "Color template",
            de: "Farbvorlage",
            ru: "Цветной шаблон",
            pt: "Modelo de cor",
            nl: "Color temp",
            fr: "Modèle de couleur",
            it: "Modello di colore",
            es: "Plantilla de color",
            pl: "Szablon",
            uk: "Колір шаблону",
            "zh-cn": "模板",
        },
        type: "boolean",
        role: "button",
        write: true,
        read: true,
        def: false,
    },
    getStatistic: {
        name: {
            en: "Statistic",
            de: "Statistik",
            ru: "Статистика",
            pt: "Estatística",
            nl: "Statistieken",
            fr: "Statistique",
            it: "Statistiche",
            es: "Estadística",
            pl: "Statystyczny",
            uk: "Статут",
            "zh-cn": "事实",
        },
        type: "boolean",
        role: "button",
        write: true,
        read: true,
        def: false,
    },
    getColors: {
        en: "Colors",
        de: "Farben",
        ru: "Цвета",
        pt: "Cores",
        nl: "Kleur",
        fr: "Couleurs",
        it: "Colori",
        es: "Colores",
        pl: "Kolor",
        uk: "Колір",
        "zh-cn": "律师",
    },
    getTemperature: {
        en: "Color temperature",
        de: "Farbtemperatur",
        ru: "Цветовая температура",
        pt: "Temperatura de cor",
        nl: "Koude temperatuur",
        fr: "Température de couleur",
        it: "Temperatura di colore",
        es: "Temperatura de color",
        pl: "Temperatura kolonu",
        uk: "Колірна температура",
        "zh-cn": "气温",
    },
    colors: {
        5569: "red",
        5570: "orange",
        5571: "yellow",
        5572: "grassgreen",
        5573: "green",
        5574: "turquoise",
        5575: "cyan",
        5576: "skyblue",
        5577: "blue",
        5578: "violet",
        5579: "magenta",
        5580: "pink",
    },
    getVoltageStatistic: {
        name: {
            en: "Voltage statistic",
            de: "Spannungsstatistik",
            ru: "Статистика напряжения",
            pt: "Estatística de tensão",
            nl: "Voltage statistieken",
            fr: "Statistiques des tensions",
            it: "Tensione statistica",
            es: "Estadística de tensión",
            pl: "Statystyczny",
            uk: "Статистика напруги",
            "zh-cn": "统计",
        },
        type: "boolean",
        role: "button",
        write: true,
        read: true,
        def: false,
    },
    getEnergyStatistic: {
        name: {
            en: "Energy statistic",
            de: "Energiestatistik",
            ru: "Энергетическая статистика",
            pt: "Estatística de energia",
            nl: "Energie statistiek",
            fr: "Statistiques de l ' énergie",
            it: "Energia statistica",
            es: "Energía estadística",
            pl: "Statystyka energetyczna",
            uk: "Енергетика",
            "zh-cn": "能源统计",
        },
        type: "boolean",
        role: "button",
        write: true,
        read: true,
        def: false,
    },
    getPowerStatistic: {
        name: {
            en: "Power statistic",
            de: "Leistungsstatistik",
            ru: "Статистика мощности",
            pt: "Estatística de energia",
            nl: "Power statistiek",
            fr: "Statistiques des pouvoirs",
            it: "Potenza statistica",
            es: "Estadística de poder",
            pl: "Statystyczny",
            uk: "Статистика потужності",
            "zh-cn": "权威统计",
        },
        type: "boolean",
        role: "button",
        write: true,
        read: true,
        def: false,
    },
    count: {
        name: {
            en: "Number of attributes of Datapoint Value",
            de: "Anzahl der Attribute von Datapoint Value",
            ru: "Количество атрибутов Datapoint Value",
            pt: "Número de atributos do Valor de Datapoint",
            nl: "Nummer van Attributen van Datapoint Value",
            fr: "Nombre d'attributs de Valeur de Datapoint",
            it: "Numero di attributi del valore di Datapoint",
            es: "Número de atributos de valor Datapoint",
            pl: "Liczba atrybutów Datapoint Value",
            uk: "Кількість атрибутів Datapoint Value",
            "zh-cn": "数据点数",
        },
        type: "number",
        role: "state",
        write: false,
        read: true,
        def: 0,
    },
    grid: {
        name: {
            en: "Time distance/resolution in seconds.",
            de: "Zeitabstand/Auflösung in Sekunden.",
            ru: "Расстояние времени/разрешение в секундах.",
            pt: "Distância/resolução de tempo em segundos.",
            nl: "Tijd afstand/resolutie in seconden.",
            fr: "Distance/résolution en quelques secondes.",
            it: "Distanza/risoluzione del tempo in pochi secondi.",
            es: "Distancia horaria/resolución en segundos.",
            pl: "Odległość czasu w sekundach.",
            uk: "Часова відстань/регуляція за секундами.",
            "zh-cn": "时间距离/决议二。.",
        },
        type: "number",
        role: "state",
        write: false,
        read: true,
        def: 0,
    },
    datatime: {
        name: {
            en: "Unix timestamp of the last update.",
            de: "Unix Zeitstempel des letzten Updates.",
            ru: "Unix timetamp последнего обновления.",
            pt: "Tamanho unix da última atualização.",
            nl: "Unix tijd van de laatste update.",
            fr: "Unix timestamp de la dernière mise à jour.",
            it: "Unix timestamp dell'ultimo aggiornamento.",
            es: "Unix timestamp de la última actualización.",
            pl: "Uniksowy numer czasowy ostatniej aktualizacji.",
            uk: "Унікс таймер останнього оновлення.",
            "zh-cn": "上次更新的时间限制。.",
        },
        type: "number",
        role: "state",
        write: false,
        read: true,
        def: 0,
    },
    value: {
        name: {
            en: "Number",
            de: "Anzahl",
            ru: "Номер",
            pt: "Número",
            nl: "Nummer",
            fr: "Nombre",
            it: "Numero",
            es: "Número",
            pl: "Numer",
            uk: "Кількість",
            "zh-cn": "数字",
        },
        type: "string",
        role: "json",
        write: false,
        read: true,
        def: "[]",
    },
    chart: {
        name: {
            en: "Chart",
            de: "Diagramm",
            ru: "Заряд",
            pt: "Gráfico",
            nl: "Grafiek",
            fr: "Graphique",
            it: "Grafico",
            es: "Chart",
            pl: "Wykres",
            uk: "Графік",
            "zh-cn": "图表",
        },
        type: "string",
        role: "json",
        write: false,
        read: true,
        def: "{}",
    },
    temp: {
        name: {
            en: "Temperature",
            de: "Temperatur",
            ru: "Температура",
            pt: "Temperatura",
            nl: "Temperatuur",
            fr: "Température",
            it: "Temperatura",
            es: "Temperatura",
            pl: "Temperatura",
            uk: "Погода",
            "zh-cn": "模范",
        },
        type: "number",
        role: "info",
        write: false,
        read: true,
        def: -1,
        min: -1,
        max: 6500,
        unit: "K",
    },
};
//<color> //Farbe oder Farbtemperatur
//<sun_simulation> //Licht Sonnenauf- und Sonnenuntergangsimulation
//<timer_control> //HKR Boost/Fenster auf/Temperatur-Override aktivieren
//<switch_master> //Geräte auf Zustand anderer Geräte schalten
exports.hue_colors = {
    sat: {
        name: {
            en: "Saturation",
            de: "Sättigung",
            ru: "Сатурация",
            pt: "Saturação",
            nl: "Saturatie",
            fr: "Saturation",
            it: "Saturazione",
            es: "Saturación",
            pl: "Saturacja",
            uk: "Зберегти",
            "zh-cn": "饱 质",
        },
        type: "number",
        role: "info",
        write: false,
        read: true,
        min: -1,
        max: 255,
        def: 0,
    },
    val: {
        name: {
            en: "Value attribute",
            de: "Wertattribut",
            ru: "Атрибутив ценности",
            pt: "Atributo de valor",
            nl: "Value Attribut",
            fr: "Indice de valeur",
            it: "Valore attributo",
            es: "Valor atributo",
            pl: "Atrybut Value",
            uk: "Значення атрибуту",
            "zh-cn": "价值归属",
        },
        type: "number",
        role: "info",
        write: false,
        read: true,
        def: 0,
    },
    hue: {
        name: {
            en: "Hue",
            de: "Hue",
            ru: "Хуэ",
            pt: "Hue",
            nl: "Hue",
            fr: "Hue",
            it: "Hue",
            es: "Hue",
            pl: "Hue",
            uk: "Ху",
            "zh-cn": "Hue Hue",
        },
        type: "number",
        role: "info",
        write: false,
        read: true,
        def: 0,
    },
};

exports.bitmasks = {
    0: "HAN-FUN Gerät",
    1: "Unbekannt",
    2: "Licht/Lampe",
    3: "Bit 3 unknown",
    4: "Alarm-Sensor",
    5: "AVM-Button",
    6: "AVM Heizkörperregler",
    7: "AVM Energie Messgerät",
    8: "Temperatursensor",
    9: "AVM Schaltsteckdose",
    10: "AVM DECT Repeater",
    11: "AVM Mikrofon",
    12: "Eine Gruppe",
    13: "HAN-FUN-Unit",
    14: "Bit 14 unknown",
    15: "an-/ausschaltbares Gerät/Steckdose/Lampe/Aktor",
    16: "Gerät mit einstellbarem Dimm-, Höhen- bzw. Niveau-Level",
    17: "Lampe mit einstellbarer Farbe/Farbtemperatur",
    18: "Rollladen(Blind) - hoch, runter, stop und level 0% bis 100 %",
    19: "Bit 19 unknown",
    20: "Luftfeuchtigkeitssensor",
};

exports.interfaces = {
    277: "(277) KEEP_ALIVE",
    256: "(256) ALERT",
    512: "(512) ON_OFF",
    513: "(513) LEVEL_CTRL",
    514: "(514) COLOR_CTRL",
    516: "(516) OPEN_CLOSE",
    517: "(517) OPEN_CLOSE_CONFIG",
    772: "(772) SIMPLE_BUTTON",
    1024: "(1024) SUOTA-Update",
};

exports.pics = {
    Blind: "/img/blinds.png",
    Button: "/img/button.png",
    100: "/img/dect100.png",
    200: "/img/dect200.png",
    210: "/img/dect210.png",
    300: "/img/dect300.png",
    301: "/img/dect301.png",
    302: "/img/dect302.png",
    DECT: "/img/dect.png",
    310: "/img/dect310.png",
    400: "/img/dect400.png",
    440: "/img/dect440.png",
    500: "/img/dect500.png",
    "546E": "/img/dect546E.png",
    1200: "/img/dect1200.png",
    1213: "/img/dect1213.png",
    1750: "/img/dect1750.png",
    2400: "/img/dect2400.png",
    3000: "/img/dect3000.png",
    Bell: "/img/dectbell.png",
    CTRL: "/img/dectctrl.png",
    Group: "/img/dectgroup.png",
    DIP: "/img/dectip.png",
    Sensor: "/img/dectsensor.png",
    Stecker: "/img/dectstecker.png",
    Taster: "/img/decttaster.png",
    FUN: "/img/dectwindow.png",
    Light: "/img/light.png",
    Power: "/img/poweroutlet.png",
    Radiator: "/img/radiator.png",
    Spar: "/img/spar.png",
    Template: "/img/template.png",
    Window: "/img/window.png",
    Unbekannt: "/img/unknown.png",
};
