exports.commons = {
	identifier: {name: "Identifier (IPEI)", typ: "mixed", role: "info", write: false}, 
	id: {name: "ID", typ: "number", role: "info", write: false}, 
	functionbitmask: {name: "Bitmask", typ: "string", role: "info", write: false}, 
	fwversion: {name: "Version", typ: "mixed", role: "info", write: false}, 
	manufacturer: {name: "Manufacturer", typ: "string", role: "info", write: false}, 
	productname: {name: "Productname", typ: "string", role: "info", write: false}, 
	present: {name: "Device online", typ: "boolean", role: "info", write: false}, 
	txbusy: {name: "Trasmitting active", typ: "boolean", role: "info", write: false}, 
	name: {name: "Name", typ: "string", role: "value", write: true}, 
	battery: {name: "Battery level", typ: "number", role: "indicator.battery", write: false}, 
	batterylow: {name: "Low Battery", typ: "boolean", role: "indicator.lowbat", write: false}, 
	celsius: {name: "actual Temperature for Alexa", typ: "number", role: "value.temperature", write: false}, 
	offset: {name: "Offset", typ: "number", role: "info", write: false}, 
	tist: {name: "Current  Temperature", typ: "number", role: "info", write: false}, 
	tsoll: {name: "Target Temperature", typ: "mixed", role: "level.temperature", write: true}, 
	absenk: {name: "night temperature", typ: "number", role: "info", write: false}, 
	komfort: {name: "comfort temperature", typ: "number", role: "info", write: false}, 
	lock: {name: "Lock API", typ: "number", role: "info", write: false}, 
	devicelock: {name: "Button device lock", typ: "number", role: "info", write: false}, 
	errorcode: {name: "Error Code", typ: "number", role: "info", write: false}, 
	windowopenactiv: {name: "Window open activ", typ: "boolean", role: "switch", write: true}, 
	windowopenactiveendtime: {name: "Actual time + Max. 24h - Value in Mintues", typ: "number", role: "timestamp", write: true}, 
	boostactive: {name: "Boost active", typ: "boolean", role: "switch", write: true}, 
	boostactiveendtime: {name: "Actual time + Max. 24h - Value in Mintues", typ: "number", role: "timestamp", write: true}, 
	endperiod: {name: "End period", typ: "number", role: "timestamp", write: false}, 
	tchange: {name: "Next temperature change", typ: "number", role: "info", write: false}, 
	summeractive: {name: "Summer active", typ: "boolean", role: "info", write: false}, 
	holidayactive: {name: "Holiday active", typ: "boolean", role: "info", write: false}, 
	state: {name: "State", typ: "boolean", role: "switch", write: true}, 
	states: {name: "State", typ: "boolean", role: "info", write: false}, 
	blindstate: {name: "Alarm", typ: "number", role: "info", write: false}, 
	simple: {name: "0=off 1=on 2=toggle", typ: "number", role: "value", write: true}, 
	mode: {name: "Mode", typ: "string", role: "info", write: false}, 
	voltage: {name: "Voltage", typ: "number", role: "info", write: false}, 
	power: {name: "Power", typ: "number", role: "info", write: false}, 
	energy: {name: "Energy", typ: "number", role: "info", write: false}, 
	lastpressedtimestamp: {name: "Last pressed timestamp", typ: "number", role: "timestamp", write: false}, 
	etsideviceid: {name: "Internal device ID", typ: "number", role: "info", write: false}, 
	unittype: {name: "Unittype", typ: "number", role: "info", write: false}, 
	interfaces: {name: "Interfaces", typ: "mixed", role: "info", write: false}, 
	lastalertchgtimestamp: {name: "Last alert timestamp", typ: "number", role: "timestamp", write: false}, 
	level: {name: "Level 0(0%) - 255(100%)", typ: "number", role: "value.level", write: true}, 
	levelpercentage: {name: "Level percentage 0-100", typ: "number", role: "level.dimmer", write: true}, 
	supported_modes: {name: "Supported modes", typ: "number", role: "info", write: false}, 
	current_mode: {name: "current mode", typ: "number", role: "info", write: false}, 
	fullcolorsupport: {name: "Full color support", typ: "boolean", role: "info", write: false}, 
	mapped: {name: "Mapped", typ: "boolean", role: "info", write: false}, 
	saturation: {name: "Saturation", typ: "number", role: "level.color.saturation", write: true}, 
	unmapped_hue: {name: "Unmapped hue", typ: "number", role: "info", write: false}, 
	unmapped_saturation: {name: "Unmapped saturation", typ: "number", role: "info", write: false}, 
	temperature: {name: "Temperature", typ: "number", role: "level.color.temperature", write: true}, 
	endpositionsset: {name: "End positions set", typ: "number", role: "info", write: false},
	hue: {name: "Hue value in degrees", typ: "number", role: "level.color.hue", write: true},
	masterdeviceid: {name: "Interne ID", typ: "number", role: "info", write: false},
	members: {name: "Group member IDs", typ: "mixed", role: "info", write: true},
	humidity: {name: "Relative Humidity", typ: "number", role: "info", write: false},
	rel_humidity: {name: "Humidity", typ: "number", role: "info", write: false},
	synchronized: {name: "synchronized", typ: "number", role: "info", write: false}
};

exports.bitmasks = { 
	Bit0: "Unbekannt", 
	Bit1: "HAN-FUN Gerät",
	Bit2: "Licht/Lampe", 
	Bit4: "Alarm-Sensor", 
	Bit5: "AVM-Button", 
	Bit6: "Heizkörperregler", 
	Bit7: "Energie Messgerät", 
	Bit8: "Temperatursensor", 
	Bit9: "Schaltsteckdose", 
	Bit10: "AVM DECT Repeater", 
	Bit11: "Mikrofon", 
	Bit12: "Eine Gruppe",
	Bit13: "HAN-FUN-Unit", 
	Bit15: "an-/ausschaltbares Gerät/Steckdose/Lampe/Aktor", 
	Bit16: "Gerät mit einstellbarem Dimm-, Höhen- bzw. Niveau-Level", 
	Bit17: "Lampe mit einstellbarer Farbe/Farbtemperatur", 
	Bit18: "Rollladen(Blind) - hoch, runter, stop und level 0% bis 100 %"
};

exports.interfaces = {
	I277: "(277) KEEP_ALIVE",
	I256: "(256) ALERT",
	I512: "(512) ON_OFF",
	I513: "(513) LEVEL_CTRL",
	I514: "(514) COLOR_CTRL",
	I516: "(516) OPEN_CLOSE",
	I517: "(517) OPEN_CLOSE_CONFIG",
	I772: "(772) SIMPLE_BUTTON",
	I1024: "(1024) SUOTA-Update"
};